PR
AIMROM/vendor_aim pull request #31
Opened 2018-02-12 18:38 UTC by sarveshrulz

2018-02-13 01:05 UTC, krasCGQ requested changes

2018-02-13 01:05 UTC, krasCGQ commented on config/caf_fw.mk
> +    telephony-ext
Device-specific

2018-02-13 01:05 UTC, krasCGQ commented on config/common_audio.mk
> +    $(NOTIFICATION_PATH)/CyanMessage.ogg:system/media/audio/notifications/CyanMessage.ogg \
I see CM-era ringtones I go away

2018-02-13 01:54 UTC, Anandnv commented on config/caf_fw.mk
> +    telephony-ext
Can be call it from device tree

2018-02-14 09:27 UTC, sarveshrulz commented on config/caf_fw.mk
> +    telephony-ext
OK sorry, some ROMs did it though...

2018-02-14 10:14 UTC, Anandnv commented on config/caf_fw.mk
> +    telephony-ext
Nhaa. We can merge it tho

2018-02-14 10:14 UTC, merged